version: '2'
services:
    rails:
        image: rails:5.0.0.1
        hostname: "${PROJECT_NAME}_rails"
        container_name: "${PROJECT_NAME}_rails"
        ports:
            - 3000:3000
        volumes:
            - "../${PROJECT_ROOT}:/usr/src/app"
        working_dir: /usr/src/app
        links:
            - postgresql
        command: [ "rails", "server", "-b", "0.0.0.0" ]
        entrypoint: ./postinstall.sh

    postgresql:
        image: postgres:9.6
        hostname: "${PROJECT_NAME}_db"
        container_name: "${PROJECT_NAME}_db"
        volumes_from:
            - data
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_DB: "${DB_NAME}"
    data:
        image: postgres:9.6
        hostname: "${PROJECT_NAME}_postgres_data"
        container_name: "${PROJECT_NAME}_postgres_data"
        volumes:
            - /var/lib/postgresql/data
        command: "true"
    pg-admin:
        image: fenglc/pgadmin4
        hostname: "${PROJECT_NAME}_pgadmin"
        container_name: "${PROJECT_NAME}_pgadmin"
        ports:
            - 5050:5050
        links:
            - postgresql:postgres
        volumes:
            - /etc/localtime:/etc/localtime
