---
production:
  user: user
  group: group
  host: example.com
  port: 22
  public_dir: "path/to/public/"
  dbname: name
  dbuser: user
  dbpassword: password
  dbhost: localhost
  exclude: "*.swp;*.gitignore"
development:
  user: user
  group: group
  host: example.com
  port: 22
  public_dir: "path/to/public/"
  dbname: name
  dbuser: user
  dbpassword: password
  dbhost: localhost
  exclude: "*.swp;*.gitignore"

